version: "3.4"
services:
    dynamo:
      command: "-jar DynamoDBLocal.jar -inMemory"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      working_dir: /home/dynamodblocal

    db:
      image: db:latest
      restart: unless-stopped
      ports:
        - "30002:30002"
      env_file:
        - .aws.env

    s1:
      image: s1:latest
      restart: unless-stopped
      ports:
        - "30000:30000"

    s2:
      image: s2:latest
      restart: unless-stopped
      ports:
        - "30001:30001"

    s3:
      image: s3:latest
      restart: unless-stopped
      ports:
        - "30003:30003"
